/// <reference path="../../../xrm.d.ts" />
/// <reference path="../../../_internal/EntityEnum/contact.d.ts" />
declare namespace Form.contact.Main {
  namespace PortalContact {
    namespace Tabs {
      interface general extends Xrm.SectionCollectionBase {
        get(name: "name"): Xrm.PageSection;
        get(name: "address"): Xrm.PageSection;
        get(name: "shipping information"): Xrm.PageSection;
        get(name: "description"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface details extends Xrm.SectionCollectionBase {
        get(name: "professional information"): Xrm.PageSection;
        get(name: "personal information"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface alerts extends Xrm.SectionCollectionBase {
        get(name: "{f0ef7388-9001-dd11-86da-0003ff48c0db}_section_5"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface webauthentication extends Xrm.SectionCollectionBase {
        get(name: "{f0ef7388-9001-dd11-86da-0003ff48c0db}_section_4"): Xrm.PageSection;
        get(name: "{f0ef7388-9001-dd11-86da-0003ff48c0db}_section_5"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface notesandactivities extends Xrm.SectionCollectionBase {
        get(name: "activities"): Xrm.PageSection;
        get(name: "notes"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface administration extends Xrm.SectionCollectionBase {
        get(name: "internal information"): Xrm.PageSection;
        get(name: "billing information"): Xrm.PageSection;
        get(name: "contact methods"): Xrm.PageSection;
        get(name: "marketing information"): Xrm.PageSection;
        get(name: "service preferences"): Xrm.PageSection;
        get(name: string): Xrm.EmptyPageSection;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "salutation"): Xrm.Attribute<string>;
      get(name: "telephone1"): Xrm.Attribute<string>;
      get(name: "firstname"): Xrm.Attribute<string>;
      get(name: "telephone2"): Xrm.Attribute<string>;
      get(name: "middlename"): Xrm.Attribute<string>;
      get(name: "mobilephone"): Xrm.Attribute<string>;
      get(name: "lastname"): Xrm.Attribute<string>;
      get(name: "fax"): Xrm.Attribute<string>;
      get(name: "jobtitle"): Xrm.Attribute<string>;
      get(name: "emailaddress1"): Xrm.Attribute<string>;
      get(name: "parentcustomerid"): Xrm.LookupAttribute;
      get(name: "adx_timezone"): Xrm.Attribute<any>;
      get(name: "adx_preferredlanguageid"): Xrm.LookupAttribute;
      get(name: "address1_addresstypecode"): Xrm.OptionSetAttribute<contact_address1_addresstypecode>;
      get(name: "address1_city"): Xrm.Attribute<string>;
      get(name: "address1_name"): Xrm.Attribute<string>;
      get(name: "address1_stateorprovince"): Xrm.Attribute<string>;
      get(name: "address1_line1"): Xrm.Attribute<string>;
      get(name: "address1_postalcode"): Xrm.Attribute<string>;
      get(name: "address1_line2"): Xrm.Attribute<string>;
      get(name: "address1_country"): Xrm.Attribute<string>;
      get(name: "address1_line3"): Xrm.Attribute<string>;
      get(name: "address1_telephone1"): Xrm.Attribute<string>;
      get(name: "address1_freighttermscode"): Xrm.OptionSetAttribute<contact_address1_freighttermscode>;
      get(name: "address1_shippingmethodcode"): Xrm.OptionSetAttribute<contact_address1_shippingmethodcode>;
      get(name: "description"): Xrm.Attribute<string>;
      get(name: "department"): Xrm.Attribute<string>;
      get(name: "accountrolecode"): Xrm.OptionSetAttribute<contact_accountrolecode>;
      get(name: "managername"): Xrm.Attribute<string>;
      get(name: "assistantname"): Xrm.Attribute<string>;
      get(name: "managerphone"): Xrm.Attribute<string>;
      get(name: "assistantphone"): Xrm.Attribute<string>;
      get(name: "gendercode"): Xrm.OptionSetAttribute<contact_gendercode>;
      get(name: "birthdate"): Xrm.DateAttribute;
      get(name: "spousesname"): Xrm.Attribute<string>;
      get(name: "anniversary"): Xrm.DateAttribute;
      get(name: "familystatuscode"): Xrm.OptionSetAttribute<contact_familystatuscode>;
      get(name: "adx_profilealert"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_profilealertdate"): Xrm.DateAttribute;
      get(name: "adx_profilealertinstructions"): Xrm.Attribute<string>;
      get(name: "adx_identity_username"): Xrm.Attribute<string>;
      get(name: "adx_identity_logonenabled"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_identity_emailaddress1confirmed"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_identity_lockoutenabled"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_identity_mobilephoneconfirmed"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_identity_lockoutenddate"): Xrm.DateAttribute;
      get(name: "adx_identity_twofactorenabled"): Xrm.OptionSetAttribute<boolean>;
      get(name: "adx_identity_accessfailedcount"): Xrm.NumberAttribute;
      get(name: "adx_identity_securitystamp"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute;
      get(name: "transactioncurrencyid"): Xrm.LookupAttribute;
      get(name: "paymenttermscode"): Xrm.OptionSetAttribute<contact_paymenttermscode>;
      get(name: "creditlimit"): Xrm.NumberAttribute;
      get(name: "defaultpricelevelid"): Xrm.LookupAttribute;
      get(name: "creditonhold"): Xrm.OptionSetAttribute<boolean>;
      get(name: "preferredcontactmethodcode"): Xrm.OptionSetAttribute<contact_preferredcontactmethodcode>;
      get(name: "donotbulkemail"): Xrm.OptionSetAttribute<boolean>;
      get(name: "donotemail"): Xrm.OptionSetAttribute<boolean>;
      get(name: "donotfax"): Xrm.OptionSetAttribute<boolean>;
      get(name: "donotphone"): Xrm.OptionSetAttribute<boolean>;
      get(name: "donotpostalmail"): Xrm.OptionSetAttribute<boolean>;
      get(name: "originatingleadid"): Xrm.LookupAttribute;
      get(name: "lastusedincampaign"): Xrm.DateAttribute;
      get(name: "donotsendmm"): Xrm.OptionSetAttribute<boolean>;
      get(name: "preferredappointmentdaycode"): Xrm.OptionSetAttribute<contact_preferredappointmentdaycode>;
      get(name: "preferredequipmentid"): Xrm.LookupAttribute;
      get(name: "preferredappointmenttimecode"): Xrm.OptionSetAttribute<contact_preferredappointmenttimecode>;
      get(name: "preferredsystemuserid"): Xrm.LookupAttribute;
      get(name: "preferredserviceid"): Xrm.LookupAttribute;
      get(name: "statecode"): Xrm.OptionSetAttribute<contact_statecode>;
      get(name: string): Xrm.EmptyAttribute;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "salutation"): Xrm.StringControl;
      get(name: "telephone1"): Xrm.StringControl;
      get(name: "firstname"): Xrm.StringControl;
      get(name: "telephone2"): Xrm.StringControl;
      get(name: "middlename"): Xrm.StringControl;
      get(name: "mobilephone"): Xrm.StringControl;
      get(name: "lastname"): Xrm.StringControl;
      get(name: "fax"): Xrm.StringControl;
      get(name: "jobtitle"): Xrm.StringControl;
      get(name: "emailaddress1"): Xrm.StringControl;
      get(name: "parentcustomerid"): Xrm.LookupControl;
      get(name: "adx_timezone"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "adx_preferredlanguageid"): Xrm.LookupControl;
      get(name: "address1_addresstypecode"): Xrm.OptionSetControl<contact_address1_addresstypecode>;
      get(name: "address1_city"): Xrm.StringControl;
      get(name: "address1_name"): Xrm.StringControl;
      get(name: "address1_stateorprovince"): Xrm.StringControl;
      get(name: "address1_line1"): Xrm.StringControl;
      get(name: "address1_postalcode"): Xrm.StringControl;
      get(name: "address1_line2"): Xrm.StringControl;
      get(name: "address1_country"): Xrm.StringControl;
      get(name: "address1_line3"): Xrm.StringControl;
      get(name: "address1_telephone1"): Xrm.StringControl;
      get(name: "address1_freighttermscode"): Xrm.OptionSetControl<contact_address1_freighttermscode>;
      get(name: "address1_shippingmethodcode"): Xrm.OptionSetControl<contact_address1_shippingmethodcode>;
      get(name: "description"): Xrm.StringControl;
      get(name: "department"): Xrm.StringControl;
      get(name: "accountrolecode"): Xrm.OptionSetControl<contact_accountrolecode>;
      get(name: "managername"): Xrm.StringControl;
      get(name: "assistantname"): Xrm.StringControl;
      get(name: "managerphone"): Xrm.StringControl;
      get(name: "assistantphone"): Xrm.StringControl;
      get(name: "gendercode"): Xrm.OptionSetControl<contact_gendercode>;
      get(name: "birthdate"): Xrm.DateControl;
      get(name: "spousesname"): Xrm.StringControl;
      get(name: "anniversary"): Xrm.DateControl;
      get(name: "familystatuscode"): Xrm.OptionSetControl<contact_familystatuscode>;
      get(name: "ContentAccessLevels"): Xrm.SubGridControl;
      get(name: "Product"): Xrm.SubGridControl;
      get(name: "WebRoles"): Xrm.SubGridControl;
      get(name: "deflectedcases"): Xrm.SubGridControl;
      get(name: "adx_profilealert"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_profilealertdate"): Xrm.DateControl;
      get(name: "adx_profilealertinstructions"): Xrm.StringControl;
      get(name: "adx_identity_username"): Xrm.StringControl;
      get(name: "adx_identity_logonenabled"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_identity_emailaddress1confirmed"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_identity_lockoutenabled"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_identity_mobilephoneconfirmed"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_identity_lockoutenddate"): Xrm.DateControl;
      get(name: "adx_identity_twofactorenabled"): Xrm.OptionSetControl<boolean>;
      get(name: "adx_identity_accessfailedcount"): Xrm.NumberControl;
      get(name: "adx_identity_securitystamp"): Xrm.StringControl;
      get(name: "adx_externalidentity"): Xrm.SubGridControl;
      get(name: "contactactivitiesgrid"): Xrm.SubGridControl;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "ownerid"): Xrm.LookupControl;
      get(name: "transactioncurrencyid"): Xrm.LookupControl;
      get(name: "paymenttermscode"): Xrm.OptionSetControl<contact_paymenttermscode>;
      get(name: "creditlimit"): Xrm.NumberControl;
      get(name: "defaultpricelevelid"): Xrm.LookupControl;
      get(name: "creditonhold"): Xrm.OptionSetControl<boolean>;
      get(name: "preferredcontactmethodcode"): Xrm.OptionSetControl<contact_preferredcontactmethodcode>;
      get(name: "donotbulkemail"): Xrm.OptionSetControl<boolean>;
      get(name: "donotemail"): Xrm.OptionSetControl<boolean>;
      get(name: "donotfax"): Xrm.OptionSetControl<boolean>;
      get(name: "donotphone"): Xrm.OptionSetControl<boolean>;
      get(name: "donotpostalmail"): Xrm.OptionSetControl<boolean>;
      get(name: "originatingleadid"): Xrm.LookupControl;
      get(name: "lastusedincampaign"): Xrm.DateControl;
      get(name: "donotsendmm"): Xrm.OptionSetControl<boolean>;
      get(name: "preferredappointmentdaycode"): Xrm.OptionSetControl<contact_preferredappointmentdaycode>;
      get(name: "preferredequipmentid"): Xrm.LookupControl;
      get(name: "preferredappointmenttimecode"): Xrm.OptionSetControl<contact_preferredappointmenttimecode>;
      get(name: "preferredsystemuserid"): Xrm.LookupControl;
      get(name: "preferredserviceid"): Xrm.LookupControl;
      get(name: "header_emailaddress1"): Xrm.StringControl;
      get(name: "header_preferredcontactmethodcode"): Xrm.OptionSetControl<contact_preferredcontactmethodcode>;
      get(name: "header_ownerid"): Xrm.LookupControl;
      get(name: "footer_statecode"): Xrm.OptionSetControl<contact_statecode>;
      get(name: string): Xrm.EmptyControl;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "general"): Xrm.PageTab<Tabs.general>;
      get(name: "details"): Xrm.PageTab<Tabs.details>;
      get(name: "alerts"): Xrm.PageTab<Tabs.alerts>;
      get(name: "web authentication"): Xrm.PageTab<Tabs.webauthentication>;
      get(name: "notes and activities"): Xrm.PageTab<Tabs.notesandactivities>;
      get(name: "administration"): Xrm.PageTab<Tabs.administration>;
      get(name: string): Xrm.EmptyPageTab;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface PortalContact extends Xrm.PageBase<PortalContact.Attributes,PortalContact.Tabs,PortalContact.Controls> {
    getAttribute(attributeName: "salutation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "telephone1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "firstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "telephone2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "middlename"): Xrm.Attribute<string>;
    getAttribute(attributeName: "mobilephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "lastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "fax"): Xrm.Attribute<string>;
    getAttribute(attributeName: "jobtitle"): Xrm.Attribute<string>;
    getAttribute(attributeName: "emailaddress1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "parentcustomerid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "adx_timezone"): Xrm.Attribute<any>;
    getAttribute(attributeName: "adx_preferredlanguageid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "address1_addresstypecode"): Xrm.OptionSetAttribute<contact_address1_addresstypecode>;
    getAttribute(attributeName: "address1_city"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_stateorprovince"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_postalcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_country"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_line3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_telephone1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "address1_freighttermscode"): Xrm.OptionSetAttribute<contact_address1_freighttermscode>;
    getAttribute(attributeName: "address1_shippingmethodcode"): Xrm.OptionSetAttribute<contact_address1_shippingmethodcode>;
    getAttribute(attributeName: "description"): Xrm.Attribute<string>;
    getAttribute(attributeName: "department"): Xrm.Attribute<string>;
    getAttribute(attributeName: "accountrolecode"): Xrm.OptionSetAttribute<contact_accountrolecode>;
    getAttribute(attributeName: "managername"): Xrm.Attribute<string>;
    getAttribute(attributeName: "assistantname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "managerphone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "assistantphone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "gendercode"): Xrm.OptionSetAttribute<contact_gendercode>;
    getAttribute(attributeName: "birthdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "spousesname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "anniversary"): Xrm.DateAttribute;
    getAttribute(attributeName: "familystatuscode"): Xrm.OptionSetAttribute<contact_familystatuscode>;
    getAttribute(attributeName: "adx_profilealert"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_profilealertdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "adx_profilealertinstructions"): Xrm.Attribute<string>;
    getAttribute(attributeName: "adx_identity_username"): Xrm.Attribute<string>;
    getAttribute(attributeName: "adx_identity_logonenabled"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_identity_emailaddress1confirmed"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_identity_lockoutenabled"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_identity_mobilephoneconfirmed"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_identity_lockoutenddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "adx_identity_twofactorenabled"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "adx_identity_accessfailedcount"): Xrm.NumberAttribute;
    getAttribute(attributeName: "adx_identity_securitystamp"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "transactioncurrencyid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "paymenttermscode"): Xrm.OptionSetAttribute<contact_paymenttermscode>;
    getAttribute(attributeName: "creditlimit"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defaultpricelevelid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "creditonhold"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "preferredcontactmethodcode"): Xrm.OptionSetAttribute<contact_preferredcontactmethodcode>;
    getAttribute(attributeName: "donotbulkemail"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "donotemail"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "donotfax"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "donotphone"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "donotpostalmail"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "originatingleadid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "lastusedincampaign"): Xrm.DateAttribute;
    getAttribute(attributeName: "donotsendmm"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "preferredappointmentdaycode"): Xrm.OptionSetAttribute<contact_preferredappointmentdaycode>;
    getAttribute(attributeName: "preferredequipmentid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "preferredappointmenttimecode"): Xrm.OptionSetAttribute<contact_preferredappointmenttimecode>;
    getAttribute(attributeName: "preferredsystemuserid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "preferredserviceid"): Xrm.LookupAttribute;
    getAttribute(attributeName: "statecode"): Xrm.OptionSetAttribute<contact_statecode>;
    getAttribute(attributeName: string): Xrm.EmptyAttribute;
    getControl(controlName: "salutation"): Xrm.StringControl;
    getControl(controlName: "telephone1"): Xrm.StringControl;
    getControl(controlName: "firstname"): Xrm.StringControl;
    getControl(controlName: "telephone2"): Xrm.StringControl;
    getControl(controlName: "middlename"): Xrm.StringControl;
    getControl(controlName: "mobilephone"): Xrm.StringControl;
    getControl(controlName: "lastname"): Xrm.StringControl;
    getControl(controlName: "fax"): Xrm.StringControl;
    getControl(controlName: "jobtitle"): Xrm.StringControl;
    getControl(controlName: "emailaddress1"): Xrm.StringControl;
    getControl(controlName: "parentcustomerid"): Xrm.LookupControl;
    getControl(controlName: "adx_timezone"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "adx_preferredlanguageid"): Xrm.LookupControl;
    getControl(controlName: "address1_addresstypecode"): Xrm.OptionSetControl<contact_address1_addresstypecode>;
    getControl(controlName: "address1_city"): Xrm.StringControl;
    getControl(controlName: "address1_name"): Xrm.StringControl;
    getControl(controlName: "address1_stateorprovince"): Xrm.StringControl;
    getControl(controlName: "address1_line1"): Xrm.StringControl;
    getControl(controlName: "address1_postalcode"): Xrm.StringControl;
    getControl(controlName: "address1_line2"): Xrm.StringControl;
    getControl(controlName: "address1_country"): Xrm.StringControl;
    getControl(controlName: "address1_line3"): Xrm.StringControl;
    getControl(controlName: "address1_telephone1"): Xrm.StringControl;
    getControl(controlName: "address1_freighttermscode"): Xrm.OptionSetControl<contact_address1_freighttermscode>;
    getControl(controlName: "address1_shippingmethodcode"): Xrm.OptionSetControl<contact_address1_shippingmethodcode>;
    getControl(controlName: "description"): Xrm.StringControl;
    getControl(controlName: "department"): Xrm.StringControl;
    getControl(controlName: "accountrolecode"): Xrm.OptionSetControl<contact_accountrolecode>;
    getControl(controlName: "managername"): Xrm.StringControl;
    getControl(controlName: "assistantname"): Xrm.StringControl;
    getControl(controlName: "managerphone"): Xrm.StringControl;
    getControl(controlName: "assistantphone"): Xrm.StringControl;
    getControl(controlName: "gendercode"): Xrm.OptionSetControl<contact_gendercode>;
    getControl(controlName: "birthdate"): Xrm.DateControl;
    getControl(controlName: "spousesname"): Xrm.StringControl;
    getControl(controlName: "anniversary"): Xrm.DateControl;
    getControl(controlName: "familystatuscode"): Xrm.OptionSetControl<contact_familystatuscode>;
    getControl(controlName: "ContentAccessLevels"): Xrm.SubGridControl;
    getControl(controlName: "Product"): Xrm.SubGridControl;
    getControl(controlName: "WebRoles"): Xrm.SubGridControl;
    getControl(controlName: "deflectedcases"): Xrm.SubGridControl;
    getControl(controlName: "adx_profilealert"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_profilealertdate"): Xrm.DateControl;
    getControl(controlName: "adx_profilealertinstructions"): Xrm.StringControl;
    getControl(controlName: "adx_identity_username"): Xrm.StringControl;
    getControl(controlName: "adx_identity_logonenabled"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_identity_emailaddress1confirmed"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_identity_lockoutenabled"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_identity_mobilephoneconfirmed"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_identity_lockoutenddate"): Xrm.DateControl;
    getControl(controlName: "adx_identity_twofactorenabled"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "adx_identity_accessfailedcount"): Xrm.NumberControl;
    getControl(controlName: "adx_identity_securitystamp"): Xrm.StringControl;
    getControl(controlName: "adx_externalidentity"): Xrm.SubGridControl;
    getControl(controlName: "contactactivitiesgrid"): Xrm.SubGridControl;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "ownerid"): Xrm.LookupControl;
    getControl(controlName: "transactioncurrencyid"): Xrm.LookupControl;
    getControl(controlName: "paymenttermscode"): Xrm.OptionSetControl<contact_paymenttermscode>;
    getControl(controlName: "creditlimit"): Xrm.NumberControl;
    getControl(controlName: "defaultpricelevelid"): Xrm.LookupControl;
    getControl(controlName: "creditonhold"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "preferredcontactmethodcode"): Xrm.OptionSetControl<contact_preferredcontactmethodcode>;
    getControl(controlName: "donotbulkemail"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "donotemail"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "donotfax"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "donotphone"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "donotpostalmail"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "originatingleadid"): Xrm.LookupControl;
    getControl(controlName: "lastusedincampaign"): Xrm.DateControl;
    getControl(controlName: "donotsendmm"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "preferredappointmentdaycode"): Xrm.OptionSetControl<contact_preferredappointmentdaycode>;
    getControl(controlName: "preferredequipmentid"): Xrm.LookupControl;
    getControl(controlName: "preferredappointmenttimecode"): Xrm.OptionSetControl<contact_preferredappointmenttimecode>;
    getControl(controlName: "preferredsystemuserid"): Xrm.LookupControl;
    getControl(controlName: "preferredserviceid"): Xrm.LookupControl;
    getControl(controlName: "header_emailaddress1"): Xrm.StringControl;
    getControl(controlName: "header_preferredcontactmethodcode"): Xrm.OptionSetControl<contact_preferredcontactmethodcode>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl;
    getControl(controlName: "footer_statecode"): Xrm.OptionSetControl<contact_statecode>;
    getControl(controlName: string): Xrm.EmptyControl;
  }
}
